Description of end
Home > utils > @stk_dataframe > end.m
end
PURPOSE
END implements the the 'end' keyword for indexing
SYNOPSIS
function idx = end(x, k, nb_indices)
DESCRIPTION
 END implements the the 'end' keyword for indexing
CROSS-REFERENCE INFORMATION
This function calls:
end END implements the the 'end' keyword for indexing
size SIZE [overloaded base function]
This function is called by:
and AND [overloaded base function]
apply APPLY maps a function to the rows or columns of a dataframe.
bsxfun BSXFUN [overloaded base function]
cat CAT [overloaded base function]
ctranspose CTRANSPOSE [overloaded base function]
disp DISP [overloaded base function]
display DISPLAY [overloaded base function]
double DOUBLE [overloaded base function]
end END implements the the 'end' keyword for indexing
eq EQ [overloaded base function]
fieldnames FIELDNAMES [overloaded base function]
ge GE [overloaded base function]
get GET [overloaded base function]
gt GT [overloaded base function]
horzcat HORZCAT [overloaded base function]
isempty ISEMPTY [overloaded base function]
ldivide LDIVIDE [overloaded base function]
le LE [overloaded base function]
lt LT [overloaded base function]
max MAX [overloaded base function]
mean MEAN [overloaded base function]
median MEDIAN [overloaded base function]
min MIN [overloaded base function]
minus MINUS [overloaded base function]
mode MODE [overloaded base function]
ne NE [overloaded base function]
or OR [overloaded base function]
plot PLOT [overloaded base function]
plus PLUS [overloaded base function]
power POWER [overloaded base function]
prod PROD [overloaded base function]
quantile QUANTILE [overloaded base function]
rdivide RDIVIDE [overloaded base function]
realpow REALPOW [overloaded base function]
set SET [overloaded base function]
size SIZE [overloaded base function]
std STD [overloaded base function]
stk_dataframe STK_DATAFRAME constructs a dataframe
stk_normalize STK_NORMALIZE [overloaded STK function]
stk_rescale STK_RESCALE [overloaded STK function]
subsasgn SUBSASGN [overloaded base function]
subsref SUBSREF [overloaded base function]
sum SUM [overloaded base function]
times TIMES [overloaded base function]
transpose TRANSPOSE [overloaded base function]
var VAR [overloaded base function]
vertcat VERTCAT [overloaded base function]
xor XOR [overloaded base function]
SOURCE CODE
% END implements the the 'end' keyword for indexing
% Copyright Notice
%
%    Copyright (C) 2013 SUPELEC
%
%    Author: Julien Bect  <julien.bect@supelec.fr>
% Copying Permission Statement
%
%    This file is part of
%
%            STK: a Small (Matlab/Octave) Toolbox for Kriging
%               (http://sourceforge.net/projects/kriging)
%
%    STK is free software: you can redistribute it and/or modify it under
%    the terms of the GNU General Public License as published by the Free
%    Software Foundation,  either version 3  of the License, or  (at your
%    option) any later version.
%
%    STK is distributed  in the hope that it will  be useful, but WITHOUT
%    ANY WARRANTY;  without even the implied  warranty of MERCHANTABILITY
%    or FITNESS  FOR A  PARTICULAR PURPOSE.  See  the GNU  General Public
%    License for more details.
%
%    You should  have received a copy  of the GNU  General Public License
%    along with STK.  If not, see <http://www.gnu.org/licenses/>.
function idx = end(x, k, nb_indices)
if nb_indices == 2,
    % using two indices (matrix-style indexing)
    idx = size(x.data, k);
else
    if nb_indices ~= 1,
        errmsg = 'stk_dataframe objects only support linear or matrix-style indexing.';
        stk_error(errmsg, 'IllegalIndexing');
    else
        % using linear indexing
        idx = numel(x.data);
    end
end
end % function
%--- tests with a univariate dataframe ----------------------------------------
%!shared x
%! x = stk_dataframe([1; 2; 3]);
%!assert (isequal (x(2:end, :), [2; 3]))
%!assert (isequal (x(2:end), [2; 3]))
%!assert (isequal (x(2, 1:end), 2))
%!assert (isequal (x(end), 3))
%--- tests with a bivariate dataframe -----------------------------------------
%!shared x
%! x = stk_dataframe([1 2; 3 4; 5 6]);
%!assert (isequal (x(2:end, :), x(2:3, :)))
%!assert (isequal (x(2, 1:end), x(2, :)))
%!assert (isequal (x(2:end, 2:end), x(2:3, 2)))
%!error x(1:end, 1:end, 1:end)
HTML documentation for STK 2.0.0, generated by M2HTML 1.5