Description of apply
Home > utils > arrays > @stk_dataframe > apply.m
apply
PURPOSE
APPLY maps a function to the rows or columns of a dataframe.
SYNOPSIS
function z = apply (x, dim, F, u)
DESCRIPTION
 APPLY maps a function to the rows or columns of a dataframe.
CROSS-REFERENCE INFORMATION
This function calls:
end END implements the the 'end' keyword for indexing
This function is called by:
max MAX [overloaded base function]
mean MEAN [overloaded base function]
median MEDIAN [overloaded base function]
min MIN [overloaded base function]
mode MODE [overloaded base function]
prod PROD [overloaded base function]
quantile QUANTILE [overloaded base function]
std STD [overloaded base function]
sum SUM [overloaded base function]
var VAR [overloaded base function]
SOURCE CODE
% APPLY maps a function to the rows or columns of a dataframe.
% Copyright Notice
%
%    Copyright (C) 2013 SUPELEC
%
%    Author: Julien Bect  <julien.bect@supelec.fr>
% Copying Permission Statement
%
%    This file is part of
%
%            STK: a Small (Matlab/Octave) Toolbox for Kriging
%               (http://sourceforge.net/projects/kriging)
%
%    STK is free software: you can redistribute it and/or modify it under
%    the terms of the GNU General Public License as published by the Free
%    Software Foundation,  either version 3  of the License, or  (at your
%    option) any later version.
%
%    STK is distributed  in the hope that it will  be useful, but WITHOUT
%    ANY WARRANTY;  without even the implied  warranty of MERCHANTABILITY
%    or FITNESS  FOR A  PARTICULAR PURPOSE.  See  the GNU  General Public
%    License for more details.
%
%    You should  have received a copy  of the GNU  General Public License
%    along with STK.  If not, see <http://www.gnu.org/licenses/>.
function z = apply (x, dim, F, u)
if nargin == 4
    uu = {u};
else
    uu = {};
end
if dim == 1
    % act along columns
    z = feval (F, x.data, uu{:}, 1);
else
    if dim ~= 2,
        stk_error ('Incorrect dimension specifier', 'IncorrectDimSpec');
    else
        % act along rows (less usual)
        z = feval (F, x.data, uu{:}, 2);
    end
end
end % function apply
HTML documentation for STK 2.1.1, generated by M2HTML 1.5