Description of bsxfun
Home > utils > arrays > @stk_dataframe > bsxfun.m
bsxfun
PURPOSE
BSXFUN [overloaded base function]
SYNOPSIS
function y = bsxfun(F, x1, x2)
DESCRIPTION
 BSXFUN [overloaded base function]
CROSS-REFERENCE INFORMATION
This function calls:
bsxfun BSXFUN [overloaded base function]
double DOUBLE [overloaded base function]
end END implements the the 'end' keyword for indexing
stk_dataframe STK_DATAFRAME constructs a dataframe
This function is called by:
and AND [overloaded base function]
bsxfun BSXFUN [overloaded base function]
eq EQ [overloaded base function]
ge GE [overloaded base function]
gt GT [overloaded base function]
ldivide LDIVIDE [overloaded base function]
le LE [overloaded base function]
lt LT [overloaded base function]
max MAX [overloaded base function]
min MIN [overloaded base function]
minus MINUS [overloaded base function]
ne NE [overloaded base function]
or OR [overloaded base function]
plus PLUS [overloaded base function]
power POWER [overloaded base function]
rdivide RDIVIDE [overloaded base function]
realpow REALPOW [overloaded base function]
times TIMES [overloaded base function]
xor XOR [overloaded base function]
SOURCE CODE
% BSXFUN [overloaded base function]
% Copyright Notice
%
%    Copyright (C) 2013 SUPELEC
%
%    Author: Julien Bect  <julien.bect@supelec.fr>
% Copying Permission Statement
%
%    This file is part of
%
%            STK: a Small (Matlab/Octave) Toolbox for Kriging
%               (http://sourceforge.net/projects/kriging)
%
%    STK is free software: you can redistribute it and/or modify it under
%    the terms of the GNU General Public License as published by the Free
%    Software Foundation,  either version 3  of the License, or  (at your
%    option) any later version.
%
%    STK is distributed  in the hope that it will  be useful, but WITHOUT
%    ANY WARRANTY;  without even the implied  warranty of MERCHANTABILITY
%    or FITNESS  FOR A  PARTICULAR PURPOSE.  See  the GNU  General Public
%    License for more details.
%
%    You should  have received a copy  of the GNU  General Public License
%    along with STK.  If not, see <http://www.gnu.org/licenses/>.
function y = bsxfun(F, x1, x2)
x1data = double (x1);
x2data = double (x2);
try
    ydata = bsxfun(F, x1data, x2data);
catch
    err = lasterror ();
    if strcmp (err.identifier, 'MATLAB:bsxfun:unsupportedBuiltin')
        % This happens in some old versions of Matlab with realpow, for
        % instance. Let's try without singleton expansion...
        ydata = feval (F, x1data, x2data);
        % TODO: manual bsxfun !!!
    else
        rethrow (err);
    end
end
% choose if the output type
if isa(x1, 'stk_dataframe'),
    y = stk_dataframe(ydata, x1.colnames);
else
    y = ydata;
end
end % function bsxfun
HTML documentation for STK 2.0.1, generated by M2HTML 1.5