Description of horzcat
Home > utils > arrays > @stk_dataframe > horzcat.m
horzcat
PURPOSE
HORZCAT [overloaded base function]
SYNOPSIS
function z = horzcat(x, y, varargin)
DESCRIPTION
 HORZCAT [overloaded base function]
CROSS-REFERENCE INFORMATION
This function calls:
double DOUBLE [overloaded base function]
end END implements the the 'end' keyword for indexing
get GET [overloaded base function]
horzcat HORZCAT [overloaded base function]
isempty ISEMPTY [overloaded base function]
size SIZE [overloaded base function]
stk_dataframe STK_DATAFRAME constructs a dataframe
This function is called by:
cat CAT [overloaded base function]
horzcat HORZCAT [overloaded base function]
plot PLOT [overloaded base function]
subsasgn SUBSASGN [overloaded base function]
SOURCE CODE
% HORZCAT [overloaded base function]
% Copyright Notice
%
%    Copyright (C) 2013 SUPELEC
%
%    Author: Julien Bect  <julien.bect@supelec.fr>
% Copying Permission Statement
%
%    This file is part of
%
%            STK: a Small (Matlab/Octave) Toolbox for Kriging
%               (http://sourceforge.net/projects/kriging)
%
%    STK is free software: you can redistribute it and/or modify it under
%    the terms of the GNU General Public License as published by the Free
%    Software Foundation,  either version 3  of the License, or  (at your
%    option) any later version.
%
%    STK is distributed  in the hope that it will  be useful, but WITHOUT
%    ANY WARRANTY;  without even the implied  warranty of MERCHANTABILITY
%    or FITNESS  FOR A  PARTICULAR PURPOSE.  See  the GNU  General Public
%    License for more details.
%
%    You should  have received a copy  of the GNU  General Public License
%    along with STK.  If not, see <http://www.gnu.org/licenses/>.
function z = horzcat(x, y, varargin)
if nargin < 2,
    y = [];
end
if isa(x, 'stk_dataframe')
    % In this case, [x y] will be an stk_dataframe also.
    x_data = double (x);
    y_data = double (y);
    if isa(y, 'stk_dataframe')
        y_colnames = get (y, 'colnames');
        y_rownames = get (y, 'rownames');
    else
        y_colnames = {};
        y_rownames = {};
    end
    %--- ROW NAMES --------------------------------------------------------
    x_rownames = get (x, 'rownames');
    if isempty(x_rownames)
        rownames = y_rownames;
    elseif ~isempty(y_rownames) && ~all(strcmp(x_rownames, y_rownames))
        stk_error(['Cannot concatenate because of incompatible row ' ...
            'names.'], 'IncompatibleRowColNames');
    else % ok, we can use x's column names
        rownames = x_rownames;
    end
    %--- COLUMN NAMES -----------------------------------------------------
    x_colnames = get (x, 'colnames');
    bx = isempty(x_colnames);
    by = isempty(y_colnames);
    if bx && by % none of the argument has row names
        colnames = {};
    else % at least of one the arguments has column names
        if bx
            x_colnames = repmat({''}, 1, size(x_data, 2));
        end
        if by
            y_colnames = repmat({''}, 1, size(y_data, 2));
        end
        colnames = [x_colnames y_colnames];
    end
    z = stk_dataframe([x_data y_data], colnames, rownames);
else % In this case, z will be a matrix.
    z = [double(x) double(y)];
end
if ~isempty(varargin),
    z = horzcat(z, varargin{:});
end
end % function horzcat
% IMPORTANT NOTE: [x y ...] fails to give the same result as horzcat(x, y, ...)
% in some releases of Octave. As a consequence, all tests must be written using
% horzcat explicitely.
%%
% Horizontal concatenation of two dataframes
%%
% Horizontal concatenation [dataframe matrix] or [matrix dataframe]
%%
% Horizontal concatenation of more than two elements
HTML documentation for STK 2.1.0, generated by M2HTML 1.5