Description of isempty
Home > utils > arrays > @stk_dataframe > isempty.m
isempty
PURPOSE
ISEMPTY [overloaded base function]
SYNOPSIS
function b = isempty(x)
DESCRIPTION
 ISEMPTY [overloaded base function]
CROSS-REFERENCE INFORMATION
This function calls:
end END implements the the 'end' keyword for indexing
isempty ISEMPTY [overloaded base function]
This function is called by:
horzcat HORZCAT [overloaded base function]
isempty ISEMPTY [overloaded base function]
max MAX [overloaded base function]
min MIN [overloaded base function]
plot PLOT [overloaded base function]
stk_sprintf_colnames STK_SPRINTF_COLNAMES returns the column names of an array
stk_sprintf_info STK_SPRINTF_INFO returns the 'info' string associated to an array
stk_sprintf_rownames STK_SPRINTF_ROWNAMES returns the row names of an array
subsasgn SUBSASGN [overloaded base function]
subsref SUBSREF [overloaded base function]
vertcat VERTCAT [overloaded base function]
SOURCE CODE
% ISEMPTY [overloaded base function]
% Copyright Notice
%
%    Copyright (C) 2013 SUPELEC
%
%    Author: Julien Bect  <julien.bect@supelec.fr>
% Copying Permission Statement
%
%    This file is part of
%
%            STK: a Small (Matlab/Octave) Toolbox for Kriging
%               (http://sourceforge.net/projects/kriging)
%
%    STK is free software: you can redistribute it and/or modify it under
%    the terms of the GNU General Public License as published by the Free
%    Software Foundation,  either version 3  of the License, or  (at your
%    option) any later version.
%
%    STK is distributed  in the hope that it will  be useful, but WITHOUT
%    ANY WARRANTY;  without even the implied  warranty of MERCHANTABILITY
%    or FITNESS  FOR A  PARTICULAR PURPOSE.  See  the GNU  General Public
%    License for more details.
%
%    You should  have received a copy  of the GNU  General Public License
%    along with STK.  If not, see <http://www.gnu.org/licenses/>.
function b = isempty(x)
b = isempty(x.data);
end % function isempty
HTML documentation for STK 2.0.3, generated by M2HTML 1.5