Description of plot
Home > utils > arrays > @stk_dataframe > plot.m
plot
PURPOSE
PLOT [overloaded base function]
SYNOPSIS
function plot (x, varargin)
DESCRIPTION
 PLOT [overloaded base function]
CROSS-REFERENCE INFORMATION
This function calls:
double DOUBLE [overloaded base function]
end END implements the the 'end' keyword for indexing
get GET [overloaded base function]
horzcat HORZCAT [overloaded base function]
isempty ISEMPTY [overloaded base function]
isequal ISEQUAL [overloaded base function]
plot PLOT [overloaded base function]
size SIZE [overloaded base function]
stk_dataframe STK_DATAFRAME constructs a dataframe
This function is called by:
plot PLOT [overloaded base function]
SOURCE CODE
% PLOT [overloaded base function]
% Copyright Notice
%
%    Copyright (C) 2013 SUPELEC
%
%    Author: Julien Bect  <julien.bect@supelec.fr>
% Copying Permission Statement
%
%    This file is part of
%
%            STK: a Small (Matlab/Octave) Toolbox for Kriging
%               (http://sourceforge.net/projects/kriging)
%
%    STK is free software: you can redistribute it and/or modify it under
%    the terms of the GNU General Public License as published by the Free
%    Software Foundation,  either version 3  of the License, or  (at your
%    option) any later version.
%
%    STK is distributed  in the hope that it will  be useful, but WITHOUT
%    ANY WARRANTY;  without even the implied  warranty of MERCHANTABILITY
%    or FITNESS  FOR A  PARTICULAR PURPOSE.  See  the GNU  General Public
%    License for more details.
%
%    You should  have received a copy  of the GNU  General Public License
%    along with STK.  If not, see <http://www.gnu.org/licenses/>.
function plot (x, varargin)
if ~ strcmp (x, 'stk_dataframe'),
    if isa (x, 'stk_dataframe')
        x = stk_dataframe (double (x), get (x, 'colnames'));
    else
        x = stk_dataframe (double (x));
    end
end
if (nargin > 1) && (~ ischar (varargin{1}))
    if size(x, 2) > 1,
        stk_error('Incorrect size for argument x.', 'IncorrectSize');
    else
        z = varargin{1};
        n = size (x, 1);
        if size (z, 1) == n,
            x = horzcat (x, z);
        elseif isequal(size (z), [1 n]),
            % special case: we tolerate that in silence...
            x = horzcat (x, z');
        end
        opts_pos = 2;
    end
else
    if size (x, 2) > 2,
        warning ('Plotting the first two columns only.'); %#ok<WNTAG>
        % TODO: implement scatter plot matrices
    end
    opts_pos = 1;
end
if nargin > opts_pos,
    opts = varargin(opts_pos:end);
else
    opts = {};
end
xx = double (x);
yy = xx(:, 2:end);
xx = xx(:, 1);
nb_outputs = size (yy, 2);
colnames = get (x, 'colnames');
if ~ isempty (colnames)
    xlab = colnames{1};
    ylab = colnames(2:end);
else
    xlab = '';
    ylab = {};
end
plot (xx, yy, opts{:});
if ~ isempty (xlab),
    stk_xlabel (xlab);
end
if ~ isempty (ylab)
    if nb_outputs == 1,
        stk_ylabel (ylab{1});
    else
        legend (ylab{:});
    end
end
end % function plot
HTML documentation for STK 2.1.1, generated by M2HTML 1.5