Description of stk_dataframe
Home > utils > arrays > @stk_dataframe > stk_dataframe.m
stk_dataframe
PURPOSE
STK_DATAFRAME constructs a dataframe
SYNOPSIS
function x = stk_dataframe (x0, colnames, rownames)
DESCRIPTION
 STK_DATAFRAME constructs a dataframe
CROSS-REFERENCE INFORMATION
This function calls:
end END implements the the 'end' keyword for indexing
set SET [overloaded base function]
This function is called by:
bsxfun BSXFUN [overloaded base function]
ctranspose CTRANSPOSE [overloaded base function]
horzcat HORZCAT [overloaded base function]
plot PLOT [overloaded base function]
subsref SUBSREF [overloaded base function]
transpose TRANSPOSE [overloaded base function]
vertcat VERTCAT [overloaded base function]
SOURCE CODE
% STK_DATAFRAME constructs a dataframe
% Copyright Notice
%
%    Copyright (C) 2013 SUPELEC
%
%    Authors:   Julien Bect       <julien.bect@supelec.fr>
%               Emmanuel Vazquez  <emmanuel.vazquez@supelec.fr>
% Copying Permission Statement
%
%    This file is part of
%
%            STK: a Small (Matlab/Octave) Toolbox for Kriging
%               (http://sourceforge.net/projects/kriging)
%
%    STK is free software: you can redistribute it and/or modify it under
%    the terms of the GNU General Public License as published by the Free
%    Software Foundation,  either version 3  of the License, or  (at your
%    option) any later version.
%
%    STK is distributed  in the hope that it will  be useful, but WITHOUT
%    ANY WARRANTY;  without even the implied  warranty of MERCHANTABILITY
%    or FITNESS  FOR A  PARTICULAR PURPOSE.  See  the GNU  General Public
%    License for more details.
%
%    You should  have received a copy  of the GNU  General Public License
%    along with STK.  If not, see <http://www.gnu.org/licenses/>.
function x = stk_dataframe (x0, colnames, rownames)
if nargin > 3,
   stk_error ('Too many input arguments.', 'TooManyInputArgs');
end
if nargin == 0  % default constructor
    x0 = zeros(0, 1);
end
x = struct ('data', x0, 'colnames', {{}}, 'rownames', {{}}, 'info', '');
x = class (x, 'stk_dataframe');
if nargin >= 2,
    x = set (x, 'colnames', colnames);
end
if nargin >= 3,
    x = set (x, 'rownames', rownames);
end
end % function stk_dataframe
HTML documentation for STK 2.0.1, generated by M2HTML 1.5