Description of stk_sprintf_info
Home > utils > arrays > @stk_dataframe > stk_sprintf_info.m
stk_sprintf_info
PURPOSE
STK_SPRINTF_INFO returns the 'info' string associated to an array
SYNOPSIS
function s = stk_sprintf_info (x)
DESCRIPTION
 STK_SPRINTF_INFO returns the 'info' string associated to an array
CROSS-REFERENCE INFORMATION
This function calls:
end END implements the the 'end' keyword for indexing
get GET [overloaded base function]
isempty ISEMPTY [overloaded base function]
stk_sprintf_info STK_SPRINTF_INFO returns the 'info' string associated to an array
This function is called by:
disp DISP [overloaded base function]
stk_sprintf_info STK_SPRINTF_INFO returns the 'info' string associated to an array
SOURCE CODE
% STK_SPRINTF_INFO returns the 'info' string associated to an array
% Copyright Notice
%
%    Copyright (C) 2013 SUPELEC
%
%    Authors:   Julien Bect       <julien.bect@supelec.fr>
%               Emmanuel Vazquez  <emmanuel.vazquez@supelec.fr>
% Copying Permission Statement
%
%    This file is part of
%
%            STK: a Small (Matlab/Octave) Toolbox for Kriging
%               (http://sourceforge.net/projects/kriging)
%
%    STK is free software: you can redistribute it and/or modify it under
%    the terms of the GNU General Public License as published by the Free
%    Software Foundation,  either version 3  of the License, or  (at your
%    option) any later version.
%
%    STK is distributed  in the hope that it will  be useful, but WITHOUT
%    ANY WARRANTY;  without even the implied  warranty of MERCHANTABILITY
%    or FITNESS  FOR A  PARTICULAR PURPOSE.  See  the GNU  General Public
%    License for more details.
%
%    You should  have received a copy  of the GNU  General Public License
%    along with STK.  If not, see <http://www.gnu.org/licenses/>.
function s = stk_sprintf_info (x)
s = get (x, 'info');
if isempty (s)
    s = stk_sprintf_info ([]);
end
end % function stk_sprintf_info
HTML documentation for STK 2.1, generated by M2HTML 1.5