Description of var
Home > utils > arrays > @stk_dataframe > var.m
var
PURPOSE
VAR [overloaded base function]
SYNOPSIS
function z = var(x, flag, dim)
DESCRIPTION
 VAR [overloaded base function]
CROSS-REFERENCE INFORMATION
This function calls:
apply APPLY maps a function to the rows or columns of a dataframe.
end END implements the the 'end' keyword for indexing
var VAR [overloaded base function]
This function is called by:
var VAR [overloaded base function]
SOURCE CODE
% VAR [overloaded base function]
% Copyright Notice
%
%    Copyright (C) 2013 SUPELEC
%
%    Author: Julien Bect  <julien.bect@supelec.fr>
% Copying Permission Statement
%
%    This file is part of
%
%            STK: a Small (Matlab/Octave) Toolbox for Kriging
%               (http://sourceforge.net/projects/kriging)
%
%    STK is free software: you can redistribute it and/or modify it under
%    the terms of the GNU General Public License as published by the Free
%    Software Foundation,  either version 3  of the License, or  (at your
%    option) any later version.
%
%    STK is distributed  in the hope that it will  be useful, but WITHOUT
%    ANY WARRANTY;  without even the implied  warranty of MERCHANTABILITY
%    or FITNESS  FOR A  PARTICULAR PURPOSE.  See  the GNU  General Public
%    License for more details.
%
%    You should  have received a copy  of the GNU  General Public License
%    along with STK.  If not, see <http://www.gnu.org/licenses/>.
function z = var(x, flag, dim)
if nargin < 2, flag = 0; end % default: normalize by N-1
if nargin < 3, dim = 1; end % default: act along columns
z = apply(x, dim, @var, flag);
end % function var
HTML documentation for STK 2.0.3, generated by M2HTML 1.5