Description of vertcat
Home > utils > arrays > @stk_dataframe > vertcat.m
vertcat
PURPOSE
VERTCAT [overloaded base function]
SYNOPSIS
function z = vertcat(x, y, varargin)
DESCRIPTION
 VERTCAT [overloaded base function]
CROSS-REFERENCE INFORMATION
This function calls:
double DOUBLE [overloaded base function]
end END implements the the 'end' keyword for indexing
get GET [overloaded base function]
isempty ISEMPTY [overloaded base function]
size SIZE [overloaded base function]
stk_dataframe STK_DATAFRAME constructs a dataframe
vertcat VERTCAT [overloaded base function]
This function is called by:
cat CAT [overloaded base function]
subsasgn SUBSASGN [overloaded base function]
vertcat VERTCAT [overloaded base function]
SOURCE CODE
% VERTCAT [overloaded base function]
% Copyright Notice
%
%    Copyright (C) 2013 SUPELEC
%
%    Author: Julien Bect  <julien.bect@supelec.fr>
% Copying Permission Statement
%
%    This file is part of
%
%            STK: a Small (Matlab/Octave) Toolbox for Kriging
%               (http://sourceforge.net/projects/kriging)
%
%    STK is free software: you can redistribute it and/or modify it under
%    the terms of the GNU General Public License as published by the Free
%    Software Foundation,  either version 3  of the License, or  (at your
%    option) any later version.
%
%    STK is distributed  in the hope that it will  be useful, but WITHOUT
%    ANY WARRANTY;  without even the implied  warranty of MERCHANTABILITY
%    or FITNESS  FOR A  PARTICULAR PURPOSE.  See  the GNU  General Public
%    License for more details.
%
%    You should  have received a copy  of the GNU  General Public License
%    along with STK.  If not, see <http://www.gnu.org/licenses/>.
function z = vertcat(x, y, varargin)
if isa(x, 'stk_dataframe')
    % In this case, [x; y] will be an stk_dataframe also.
    y_data = double(y);
    data = [double(x); y_data];
    if isa(y, 'stk_dataframe')
        y_colnames = get (y, 'colnames');
        y_rownames = get (y, 'rownames');
    else
        y_colnames = {};
        y_rownames = {};
    end
    %--- COLUMN NAMES -----------------------------------------------------
    x_colnames = get (x, 'colnames');
    if isempty (x_colnames)
        colnames = y_colnames;
    elseif ~isempty(y_colnames) && ~all(strcmp(x_colnames, y_colnames))
        stk_error(['Cannot concatenate because of incompatible column ' ...
            'names.'], 'IncompatibleColNames');
    else % ok, we can use x's column names
        colnames = x_colnames;
    end
    %--- ROW NAMES --------------------------------------------------------
    x_rownames = get (x, 'rownames');
    bx = isempty(x_rownames);
    by = isempty(y_rownames);
    if bx && by, % none of the argument has row names
        rownames = {};
    else % at least of one the arguments has row names
        if bx
            x_rownames = repmat({''}, size(x.data, 1), 1);
        end
        if by
            y_rownames = repmat({''}, size(y_data, 1), 1);
        end
        rownames = [x_rownames; y_rownames];
    end
    z = stk_dataframe(data, colnames, rownames);
else  % In this case, z will be a matrix.
    z = [double(x); double(y)];
end
if ~isempty(varargin),
    z = vertcat(z, varargin{:});
end
end % function subsref
% IMPORTANT NOTE: [x; y; ...] fails to give the same result as vertcat(x, y,
% ...) in some releases of Octave. As a consequence, all tests must be written
% using horzcat explicitely.
%%
% Vertical concatenation of two dataframes
%%
% Vertical concatenation [dataframe; matrix]
%%
% Vertical concatenation [matrix; dataframe]
%%
% Vertical concatenation of more than two elements
HTML documentation for STK 2.0.2, generated by M2HTML 1.5