<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
                "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
<head>
  <title>STK {STK_VERSION_NUMBER} index</title>
  <meta name="keywords" content="{DIRS}">
  <meta name="description" content="{DIRS}">
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <meta name="generator" content="m2html v1.5 &copy; 2003-2005 Guillaume Flandin">
  <meta name="robots" content="index, follow">
  <link type="text/css" rel="stylesheet" href="{MASTERPATH}m2html.css">
</head>
<body>
<a name="_top"></a>
<h1>STK {STK_VERSION_NUMBER} index</h1>
<h2>STK Directories</h2>
<ul style="list-style-image:url({MASTERPATH}octave-sombrero.png)">
<!-- BEGIN rowdir -->
<li><a href="{L_DIR}">{DIR}</a></li>
<!-- END rowdir -->
</ul>
<h2>M-files found in these directories</h2>
<table width="100%">
	<!-- BEGIN idrow -->
	<tr>
		<!-- BEGIN idcolumn -->
		<td><a href="{L_IDNAME}" title="{T_IDNAME}">{IDNAME}</a></td>
		<!-- END idcolumn -->
	</tr>
	<!-- END idrow -->
</table>

<!-- BEGIN search -->
<h2>Search Engine</h2>
<form class="search" action="{PHPFILE}" method="get">
Search for <input class="search" type="text" name="query" value="" size="20" accesskey="s"/>
<input type="submit" name="submit" value="Search">
</form>
<!-- END search -->

<!-- BEGIN graph -->
<h2>Dependency Graph</h2>
<ul style="list-style-image:url({MASTERPATH}simulinkicon.gif)">
<li>View the <a href="{LGRAPH}">Graph</a>.</li>
</ul>
<!-- END graph -->

<hr>

<address>
   HTML documentation for <strong>STK {STK_VERSION_NUMBER}</strong>,
   generated by <strong>
   <a href="{M2HTML_URL}" title="M2HTML website">{M2HTML_VERSION}</a></strong>
</address>

</body>
</html>
