Description of stk_factorialdesign
Home > utils > arrays > @stk_factorialdesign > stk_factorialdesign.m
stk_factorialdesign
PURPOSE
STK_FACTORIALDESIGN constructs a factorial design
SYNOPSIS
function x = stk_factorialdesign(levels, varargin)
DESCRIPTION
 STK_FACTORIALDESIGN constructs a factorial design
CROSS-REFERENCE INFORMATION
This function calls:
ndgrid NDGRID [overloaded base function]
set SET [overloaded base function]
This function is called by:
set SET [overloaded base function]
SOURCE CODE
% STK_FACTORIALDESIGN constructs a factorial design
% Copyright Notice
%
%    Copyright (C) 2013 SUPELEC
%
%    Author: Julien Bect  <julien.bect@supelec.fr>
% Copying Permission Statement
%
%    This file is part of
%
%            STK: a Small (Matlab/Octave) Toolbox for Kriging
%               (http://sourceforge.net/projects/kriging)
%
%    STK is free software: you can redistribute it and/or modify it under
%    the terms of the GNU General Public License as published by the Free
%    Software Foundation,  either version 3  of the License, or  (at your
%    option) any later version.
%
%    STK is distributed  in the hope that it will  be useful, but WITHOUT
%    ANY WARRANTY;  without even the implied  warranty of MERCHANTABILITY
%    or FITNESS  FOR A  PARTICULAR PURPOSE.  See  the GNU  General Public
%    License for more details.
%
%    You should  have received a copy  of the GNU  General Public License
%    along with STK.  If not, see <http://www.gnu.org/licenses/>.
function x = stk_factorialdesign(levels, varargin)
if nargin == 0  % default constructor
    levels = {[]};
end
% number of factors
d = length(levels);
if ~iscell(levels) || (numel(levels) ~= d)
    errmsg = 'Expecting a "flat" cell array as first argument.';
    stk_error(errmsg, 'TypeMismatch');
else
    if ~all(cellfun(@isnumeric, levels))
        errmsg = 'Only numeric factors are currently supported.';
        stk_error(errmsg, 'TypeMismatch');
    else % ok, numeric levels, we know how to handle that
        if (d == 0) || any(cellfun(@isempty, levels))
            xdata = zeros(0, d);
        elseif d == 1
            xdata = levels{1}(:);
        else
            % coordinate arrays
            coord = cell(1, d);
            [coord{:}] = ndgrid(levels{:});
            % design matrix
            xdata = zeros(numel(coord{1}), d);
            for j = 1:d,
                xdata(:, j) = coord{j}(:);
            end
        end
        % base dataframe
        df = stk_dataframe (xdata, varargin{:});
        df = set (df, 'info', 'Created by stk_factorialdesign');
        % "factorial design" object
        x = struct ('levels', {levels});
        x = class (x, 'stk_factorialdesign', df);
    end % if
end % if
end % function stk_factorialdesign
%--- constructor --------------------------------------------------------------
% tests some incorrect values for 'levels'
% categorical variable not supported yet
%--- disp & display -----------------------------------------------------------
%--- size, length, end --------------------------------------------------------
%--- cat, vertcat, horzcat ----------------------------------------------------
% Note: the output is a plain stk_dataframe
%--- apply & related functions ------------------------------------------------
%--- bsxfun & related functions -----------------------------------------------
%--- transpose, ctranspose ----------------------------------------------------
% Transposing a dataframe that represents a factorial design results in a
% dataframe that does NOT represent a factorial design
HTML documentation for STK 2.0.0, generated by M2HTML 1.5